### ISSUE TITLE
[BUG] TypeError when the plot doesnt have a Copy time

### ISSUE THREAD

**Issue by StephenR19** [njtnestor/chia-plot-simulator#1]
Hi noticed a small bug when you don't have a copy time you get a console error:

Uncaught (in promise) TypeError: Cannot read property 'phaseOne' of undefined
    at f.processPlotLogs (2520875.js:1)
    at 2520875.js:1. 

When you plot in the same directory it doesn't have a "Copy Time" 

Not a big issue as I can just add in a fake copy time

**Comment by njtnestor** [comment]
We are dealing with this in this trello [feature](https://trello.com/c/BVlxVXUB/19-render-incomplete-plots-if-at-least-one-phase-has-been-completed)

**Comment by mariaalonsodev** [comment]
Thank you for reporting the bug! It is now fixed and deployed.
