### ISSUE TITLE
Copy time should be included in the total duration

### ISSUE THREAD

**Issue by djdd87** [njtnestor/chia-plot-simulator#10]
Currently the duration shown when hovering over the plots doesn't include the copy time, it only includes the total time from the Chia logs, e.g.

> Total time = 22075.001 seconds. CPU (130.390%) Tue May 25 01:49:55 2021

And not the copy time, e.g.

> Copy time = 1315.210 seconds. CPU (4.000%) Tue May 25 02:11:51 2021

That total time is the total of the 4 phases added together, so the time shown is exclusive of the time spent copying. When copying across to network drives, this can be 20-30 minutes over a gigabit connection (depending on network congestion), so having this information would be useful.

I propose that the total is actually "Total time" + "Copy time"

I will create a pull request shortly.

**Comment by mariaalonsodev** [comment]
We've just merged your pull request. We did some visual changes to your solution and it's now fully integrated and deployed.

Thank you for your collaboration!

**Comment by djdd87** [comment]
Hi @HelloYouAgain, you've made this worse now. There's no longer a total duration anywhere?

![image](https://user-images.githubusercontent.com/22151993/120281906-700f8f80-c2b1-11eb-804a-f8d90e489ec9.png)

The start and end times are there, but no one is going to want to calculate that manually every time.

**Comment by mariaalonsodev** [comment]
The second column of the left table displays 16:16:16 for the first plot log. This is the total time (Phase 1 + Phase 2 + Phase 3 + Phase 4 + Copy Time) in HH:mm:ss format

Is there any reason why the total time should be in the hover modal instead of as a column in the left table?

**Comment by djdd87** [comment]
Doh! I hadn't noticed that change! Apologies - all good :)

**Comment by mariaalonsodev** [comment]
No problem! We hope to see you again 
Thank you
