### ISSUE TITLE
Safari back double data

### ISSUE THREAD

**Issue by eaglemoor** [njtnestor/chia-plot-simulator#13]
If you open https://www.chiaplotsimulator.com/?data=y2hz4tca-y46dvqxc, after go to another link (about) and press Go Back you will have double data. 
<img width="1126" alt="Screenshot 2021-06-02 at 02 37 59" src="https://user-images.githubusercontent.com/1461295/120402768-8e29ce00-c34b-11eb-964f-2f2c55052195.png">

**Comment by njtnestor** [comment]
Wow! Thanks for reporting this curious bug. We have created a [task](https://trello.com/c/9IWPSOsI/43-on-move-page-plots-that-have-been-shared-will-be-duplicated) in our trello so you can track it. We will fix it as quickly as possible.

**Comment by njtnestor** [comment]
Fixed in the last version. Thank for report the issue.
