### ISSUE TITLE
feature request: directories

### ISSUE THREAD

**Issue by syadnom** [njtnestor/chia-plot-simulator#2]
Great visualization.  What would be really nice is to show the tmp and dst directory that was used in the plot.  Would be excellent to see the delays based on drive type and so on.

**Comment by njtnestor** [comment]
We are dealing with this in this trello [feature](https://trello.com/c/FD4nTjK7/21-identify-disk-temp-and-destination-name)

**Comment by syadnom** [comment]
nice, thanks.

**Comment by njtnestor** [comment]
This featured has been released in the last version. You can check it.
