### ISSUE TITLE
[BUG] Can not add a log file

### ISSUE THREAD

**Issue by ghost** [njtnestor/chia-plot-simulator#4]
I tried multiple plot logs and non of them are working (they are complete).
I compared the log file from the repository and mine. The main difference is that I am not using the bitfield, also Backpropagation logs are different.
Here is an example:
[plotter_log_d273cfa4-fab1-4f99-8825-445c11fec409.txt](https://github.com/njtnestor/chia-plot-simulator/files/6504435/plotter_log_d273cfa4-fab1-4f99-8825-445c11fec409.txt)
Chia version 1.1.5 (if it matters)

Also this is what I find from the console:
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined at 3568d16.js:1

**Comment by ghost** [comment]
Yes, definitely, found the issue. It is because of the bitfield.
Created another log file with bitfield (enabled) and it works fine.

**Comment by njtnestor** [comment]
> Yes, definitely, found the issue. It is because of the bitfield.
> Created another log file with bitfield (enabled) and it works fine.

A fix has been deployed right now. You can check it and close the issue if is resolved.

**Comment by ghost** [comment]
> > Yes, definitely, found the issue. It is because of the bitfield.
> > Created another log file with bitfield (enabled) and it works fine.
> 
> A fix has been deployed right now. You can check it and close the issue if is resolved.

Good job ;),
Thanks, works perfectly!
