### ISSUE TITLE
Feature request: Share result with an URI

### ISSUE THREAD

**Issue by FuNK3Y** [njtnestor/chia-plot-simulator#6]
Once the logs are imported, it would be awesome to be able to share the results using an URI.

Something like https://www.chiaplotsimulator.com/?data=... where data could be a base64 encoded JSON containing the plots and their details.

**Comment by njtnestor** [comment]
We have it in mind, you can follow the tracking in this trello [feaure](https://trello.com/c/VFsyZjXq/8-share-with-json-code)

**Comment by njtnestor** [comment]
Deployed in the last version.
This task has been more difficult than previously thought due to the architecture of the platform. We have finally decided to change the architecture. Anyway it is in beta phase and we will need feedback.
