### ISSUE TITLE
Let "phaseCopy" be optional

### ISSUE THREAD

**Issue by rightpeter** [njtnestor/chia-plot-simulator#9]
I'm using same folder for both `tmp` and `dst`. As a result, there's no "Copy time" in the log which seems cause the simulator failed to load the log.

I guess it makes sense to let `phaseCopy` to be optional.

**Comment by njtnestor** [comment]
Thank you! We are dealing with this in this trello [feature](https://trello.com/c/BVlxVXUB/19-render-incomplete-plots-if-at-least-one-phase-has-been-completed)

**Comment by rightpeter** [comment]
Ah, sorry for that. Closing it.

**Comment by njtnestor** [comment]
Duplicate of https://github.com/njtnestor/chia-plot-simulator/issues/2
